apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: test:latest
    workingDir: /app
    command: ["python"]
    args: ["-m", "pytest"]
    imagePullPolicy: Never
    envFrom:
      - configMapRef:
          name: sources
  restartPolicy: Never
